java:
  runtime:
    version: 1.8.0_291

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/gamestore
    username: postgres
    password: futureiscoming

    initialization-mode: always

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true


  thymeleaf:
    enabled: true
    encoding: UTF-8